answer = int(input("give a whole number that is less than 12.\nhere>>"))
print (answer < 12) 
ren = int(input("give a grater than 45\n>"))
print (ren > 45)
run = int(input("get a number less than 30\n>"))
print(run < 30)
fan = int(input("input a number grater than 2\n>"))
print(fan > 2)
face = input("what is 2 plus 3\n>")
print (face == "5")